Repository Pithia-2/pithia-2, pull requests merged in 2019-11, with the labels that each got.

#7 Added developer names to readme
  README.md
Labels: enhancement

#8 Added GlobalConstants file
  src/pithia2/GlobalConstants.java
  src/pithia2/Views/Home.java
  src/pithia2/Views/Login.java
Labels: enhancement

#13 Redesigned login page - App now gets look and feel from user's OS
  src/pithia2/Controllers/Main.java
  src/pithia2/Views/Login.form
  src/pithia2/Views/Login.java
Labels: enhancement

#16 Fixed broken sign in button - Added error label to login page
  src/pithia2/Views/Login.form
  src/pithia2/Views/Login.java
Labels: bug, enhancement

#17 Home page redesign
  src/pithia2/Views/Home.form
  src/pithia2/Views/Home.java
  src/resources/ihu.png
  src/resources/images.jpg
Labels: enhancement

#18 Standardized new frame creation and removed redundant imports
  src/pithia2/Controllers/Main.java
  src/pithia2/Views/Home.java
  src/pithia2/Views/Login.java
Labels: enhancement

#19 made Objects Serializable
  src/pithia2/Models/Administrator.java
  src/pithia2/Models/Department.java
  src/pithia2/Models/Lesson.java
  src/pithia2/Models/RegisteredLesson.java
  src/pithia2/Models/Registration.java
  src/pithia2/Models/Student.java
  src/pithia2/Models/University.java
Labels: enhancement

#23 Βasic student GUI
  src/pithia2/Models/Registration.java
  src/pithia2/Views/Home.java
  src/pithia2/Views/LessonRegistration.form
  src/pithia2/Views/LessonRegistration.java
  src/pithia2/Views/Login.java
  src/pithia2/Views/PasswordChange.form
  src/pithia2/Views/PasswordChange.java
  src/pithia2/Views/StudentGrades.form
  src/pithia2/Views/StudentGrades.java
  src/pithia2/Views/StudentInfo.form
  src/pithia2/Views/StudentInfo.java
Labels: enhancement

#36 Removed home button from StudentInfo
  src/pithia2/Views/StudentInfo.form
  src/pithia2/Views/StudentInfo.java
Labels: enhancement

#44 Signing out now deletes the user instance
  src/pithia2/Models/Administrator.java
  src/pithia2/Models/Student.java
  src/pithia2/Models/User.java
  src/pithia2/Views/AdminGrades.java
  src/pithia2/Views/AdminHome.java
  src/pithia2/Views/Home.java
  src/pithia2/Views/LessonRegistration.java
  src/pithia2/Views/Login.java
  src/pithia2/Views/PasswordChange.java
  src/pithia2/Views/StudentGrades.java
  src/pithia2/Views/StudentInfo.java
  src/pithia2/Views/UserManagement.java
Labels: enhancement

#48 Fixed department import missing from StudentInfo
  src/pithia2/Views/StudentInfo.java
Labels: bug

#54 Test data creation code
  src/pithia2/Controllers/Main.java
  src/pithia2/Models/Lesson.java
  src/pithia2/Views/Home.form
  src/pithia2/Views/Home.java
  src/pithia2/Views/PasswordChange.java
Labels: enhancement

#60 Updated name of object output folder in .gitignore
  .gitignore
Labels: bug

#63 Student grades GUI
  src/pithia2/Views/StudentGrades.form
  src/pithia2/Views/StudentGrades.java
Labels: enhancement

#65 Implementation of student registrations
  src/pithia2/Models/RegisteredLesson.java
  src/pithia2/Models/Student.java
  src/pithia2/Views/LessonRegistration.form
  src/pithia2/Views/LessonRegistration.java
  src/pithia2/Views/NewRegistration.form
  src/pithia2/Views/NewRegistration.java
Labels: enhancement

#68 Class and function naming improvements - Removed unused code and imports
  src/pithia2/Models/User.java
  src/pithia2/Views/AdminGrades.java
  src/pithia2/Views/AdminInfo.form
  src/pithia2/Views/AdminInfo.java
  src/pithia2/Views/Departments.java
  src/pithia2/Views/Home.java
  src/pithia2/Views/LessonRegistration.java
  src/pithia2/Views/LessonsList.java
  src/pithia2/Views/Login.java
  src/pithia2/Views/NewRegistration.java
  src/pithia2/Views/PasswordChange.java
  src/pithia2/Views/StudentInfo.java
  src/pithia2/Views/UserManagement.java
Labels: enhancement

#69 Fixed duplicate code in LessonList class
  src/pithia2/Views/LessonsList.form
  src/pithia2/Views/LessonsList.java
Labels: enhancement
